version: '3.8'

services:
  cvi-frontend:
    build:
      context: ./cvi-frontend
      dockerfile: Dockerfile
    container_name: cvi-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.cloudvortexinnovation.com
      - NEXT_PUBLIC_SITE_URL=https://cloudvortexinnovation.com
    restart: unless-stopped
    networks:
      - cvi-network
    profiles:
      - frontend

  cvi-admin:
    build:
      context: ./cvi-admin
      dockerfile: Dockerfile
    container_name: cvi-admin
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://cvi-backend:3002
    restart: unless-stopped
    depends_on:
      - cvi-backend
    networks:
      - cvi-network
    profiles:
      - admin

  cvi-backend:
    build:
      context: ./cvi-backend
      dockerfile: Dockerfile
    container_name: cvi-backend
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      # Database configuration - replace with your actual values
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_TYPE=mysql
      # JWT configuration
      - JWT_SECRET=${JWT_SECRET}
      # MySQL Configuration
      - DB_SYNCHRONIZE=false
      - DB_TIMEZONE=Z
    restart: unless-stopped
    networks:
      - cvi-network
    profiles:
      - backend

networks:
  cvi-network:
    driver: bridge
